.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. flurbo_qt test_flurbo_qt
clean: FORCE
	$(MAKE) -C .. flurbo_qt_clean test_flurbo_qt_clean
check: FORCE
	$(MAKE) -C .. test_flurbo_qt_check
flurbo-qt flurbo-qt.exe: FORCE
	 $(MAKE) -C .. flurbo_qt
